[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift-codegen = "0.116.1"
cranelift-frontend = "0.116.1"
cranelift-module = "0.116.1"
cranelift-object = "0.116.1"
target-lexicon = "0.13.2"
